[package]
name = "guarakapa"
version = "0.6.0"
edition = "2018"

[dependencies]
openssl = "0.10"
rand = "0.8"
serde = { version = "1", features = ["derive"] }
bincode = "1.3"
anyhow = "1"
crossterm = "0.17"
nix = "0.17"
x11-clipboard = "0.5"
