[package]
name = "guarakapa"
version = "0.3.0"
edition = "2018"

[dependencies]
openssl = "0.10"
rand = "0.8"
scanpw = { git = "https://github.com/yds12/scanpw" }
serde = { version = "1", features = ["derive"] }
bincode = "1.3"
anyhow = "1"
